# syntax=docker/dockerfile:1

ARG BASE_IMAGE
FROM ${BASE_IMAGE}

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

ARG OCI_SOURCE="unknown"
ARG OCI_REVISION="unknown"
ARG OCI_CREATED="unknown"
ARG OCI_DESCRIPTION="unknown"
ARG CSCS_ALPS_GIT_COMMIT_SHORT="unknown"

LABEL org.opencontainers.image.source="${OCI_SOURCE}" \
      org.opencontainers.image.revision="${OCI_REVISION}" \
      org.opencontainers.image.created="${OCI_CREATED}" \
      org.opencontainers.image.description="${OCI_DESCRIPTION}" \
      com.cscs.alps.git.repo="${OCI_SOURCE}" \
      com.cscs.alps.git.commit="${OCI_REVISION}" \
      com.cscs.alps.git.commit_short="${CSCS_ALPS_GIT_COMMIT_SHORT}"

# System deps
COPY Alps-Images/common/package-helpers.sh /opt/alps/package-helpers.sh
RUN set -eux; \
    source /opt/alps/package-helpers.sh; \
    apt_get update; \
    apt_get install -y --no-install-recommends \
      ca-certificates \
      curl \
      git \
      pkg-config \
      python3-dev \
      python3-venv; \
    rm -rf /var/lib/apt/lists/*
# Python deps 
COPY Alps-Images/apps/sfttrainer/sources/requirements.txt /tmp/requirements.txt
RUN set -eux; \
    source /opt/alps/package-helpers.sh; \
    pip_install python -r /tmp/requirements.txt
