# syntax=docker/dockerfile:1

# Special thanks to Eduard Durech for his work on the original VeRL image for Alps.

ARG BASE_IMAGE
FROM ${BASE_IMAGE}

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

ARG OCI_SOURCE="unknown"
ARG OCI_REVISION="unknown"
ARG OCI_CREATED="unknown"
ARG OCI_DESCRIPTION="unknown"
ARG CSCS_ALPS_GIT_COMMIT_SHORT="unknown"

LABEL org.opencontainers.image.source="${OCI_SOURCE}" \
      org.opencontainers.image.revision="${OCI_REVISION}" \
      org.opencontainers.image.created="${OCI_CREATED}" \
      org.opencontainers.image.description="${OCI_DESCRIPTION}" \
      com.cscs.alps.git.repo="${OCI_SOURCE}" \
      com.cscs.alps.git.commit="${OCI_REVISION}" \
      com.cscs.alps.git.commit_short="${CSCS_ALPS_GIT_COMMIT_SHORT}"


ARG VERL_REF="v0.8.0"

COPY Alps-Images/common/package-helpers.sh /opt/alps/package-helpers.sh

# Install dependencies for VeRL from pypi, including vLLM and SGLang.

#Note: disable vllm installation for now, as it causes issues. To re-enable consider using the ngc vllm base image.
#RUN source /opt/alps/package-helpers.sh && pip_install python vllm --extra-index-url https://download.pytorch.org/whl/cu131

RUN set -eux; \
    source /opt/alps/package-helpers.sh; \
    pip_install python sglang[all]
RUN set -eux; \
    source /opt/alps/package-helpers.sh; \
    pip_install python flash-attn --no-build-isolation


# Install dependencies for VeRL from source, including flashinfer, flash-attention, torch_memory_saver, XIELU

ENV SRC_DIR=/workspace/src \
    WHL_DIR=/workspace/src/wheels

WORKDIR ${SRC_DIR}


#RUN git clone https://github.com/nickjbrowning/XIELU.git ;\
#    cd XIELU ;\
#    git submodule update --init --recursive ;\
#    python -m build --wheel --no-isolation --outdir=${WHL_DIR} 2>&1 | tee ./build.log
#RUN source /opt/alps/package-helpers.sh && pip_install python --no-deps --no-cache-dir --force-reinstall ${WHL_DIR}/xielu*.whl


WORKDIR /workspace

RUN rm -rf ${SRC_DIR}

RUN git clone --branch ${VERL_REF} --depth 1 https://github.com/verl-project/verl
RUN set -eux; \
    source /opt/alps/package-helpers.sh; \
    cd verl; \
    pip_install python --no-deps -e ".[sglang]"

RUN set -eux; \
    source /opt/alps/package-helpers.sh; \
    pip_install python -U "ray[data,train,tune,serve]"
RUN set -eux; \
    source /opt/alps/package-helpers.sh; \
    pip_install python "tensordict==0.10.0" omegaconf hydra-core codetiming peft pylatexenc wandb TransferQueue==0.1.6
RUN pip uninstall kernels -y --break-system-packages

RUN set -eux; \
    source /opt/alps/package-helpers.sh; \
    pip_install python cupy-cuda13x
RUN set -eux; \
    source /opt/alps/package-helpers.sh; \
    pip_install python cachetools

# Tests shipped with the image
COPY Alps-Images/apps/verl/tests/ /opt/tests/verl/
RUN find /opt/tests/verl -name "*.sh" -exec chmod a+x {} \; && \
    chmod -R a+rX /opt/tests/verl
